--------------------------------------------------------
--  Fichier créé - mercredi-novembre-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GESTION_EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EMPLOYE" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRERSS" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"ID_PUBLICUTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_LOCATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_LOCATION" 
   (	"ID_LOCATION" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"CIN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_LOCAUX
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_LOCAUX" 
   (	"COORDONNES" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATES" VARCHAR2(20 BYTE), 
	"SURFACE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_MATERIEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_MATERIEL" 
   (	"NUM_SERIE" NUMBER, 
	"QUANTITER" NUMBER, 
	"PRIX" NUMBER, 
	"NOM_MATERIEL" VARCHAR2(20 BYTE), 
	"NOM_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"COORDONEE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_PUBLICITE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PUBLICITE" 
   (	"ID_PUBLICITE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATES" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_VEHICULE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_VEHICULE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"DATE_ENTRE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"COULEUR" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENTRETIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ENTRETIENT" 
   (	"CIN" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UTILISATION" 
   (	"NUM_SERIE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_EMPLOYE
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_LOCATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_LOCAUX
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_MATERIEL
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_PUBLICITE
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_VEHICULE
SET DEFINE OFF;
REM INSERTING into SYSTEM.ENTRETIENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.UTILISATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index GESTION_EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_EMPLOYE_PK" ON "SYSTEM"."GESTION_EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_LOCATION_PK" ON "SYSTEM"."GESTION_LOCATION" ("ID_LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_LOCAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_LOCAUX_PK" ON "SYSTEM"."GESTION_LOCAUX" ("COORDONNES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_MATERIEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_MATERIEL_PK" ON "SYSTEM"."GESTION_MATERIEL" ("NUM_SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_PUBLICITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_PUBLICITE_PK" ON "SYSTEM"."GESTION_PUBLICITE" ("ID_PUBLICITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GESTION_VEHICULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_VEHICULE_PK" ON "SYSTEM"."GESTION_VEHICULE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GESTION_EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_EMPLOYE" ADD CONSTRAINT "GESTION_EMPLOYE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_LOCATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_LOCATION" ADD CONSTRAINT "GESTION_LOCATION_PK" PRIMARY KEY ("ID_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_LOCATION" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_LOCATION" MODIFY ("ID_LOCATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_LOCAUX
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_LOCAUX" ADD CONSTRAINT "GESTION_LOCAUX_PK" PRIMARY KEY ("COORDONNES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_LOCAUX" MODIFY ("COORDONNES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_MATERIEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_MATERIEL" ADD CONSTRAINT "GESTION_MATERIEL_PK" PRIMARY KEY ("NUM_SERIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_MATERIEL" MODIFY ("NUM_SERIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_PUBLICITE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_PUBLICITE" ADD CONSTRAINT "GESTION_PUBLICITE_PK" PRIMARY KEY ("ID_PUBLICITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_PUBLICITE" MODIFY ("ID_PUBLICITE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GESTION_VEHICULE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_VEHICULE" ADD CONSTRAINT "GESTION_VEHICULE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_VEHICULE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GESTION_EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_EMPLOYE" ADD CONSTRAINT "ID_PUBLICITE_FK" FOREIGN KEY ("ID_PUBLICUTE")
	  REFERENCES "SYSTEM"."GESTION_PUBLICITE" ("ID_PUBLICITE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_LOCATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_LOCATION" ADD CONSTRAINT "CIN_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "SYSTEM"."GESTION_EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_LOCAUX
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_LOCAUX" ADD CONSTRAINT "CIN_FK" FOREIGN KEY ("SURFACE")
	  REFERENCES "SYSTEM"."GESTION_EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GESTION_MATERIEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_MATERIEL" ADD CONSTRAINT "COORDONNE_FK" FOREIGN KEY ("NOM_MATERIEL")
	  REFERENCES "SYSTEM"."GESTION_LOCAUX" ("COORDONNES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTRETIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ENTRETIENT" ADD CONSTRAINT "CIN_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "SYSTEM"."GESTION_EMPLOYE" ("CIN") ENABLE;
  ALTER TABLE "SYSTEM"."ENTRETIENT" ADD CONSTRAINT "MATRICULE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "SYSTEM"."GESTION_VEHICULE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."UTILISATION" ADD CONSTRAINT "CIN_F_K" FOREIGN KEY ("NUM_SERIE")
	  REFERENCES "SYSTEM"."GESTION_EMPLOYE" ("CIN") ENABLE;
  ALTER TABLE "SYSTEM"."UTILISATION" ADD CONSTRAINT "NUM_SERIE_FK1" FOREIGN KEY ("NUM_SERIE")
	  REFERENCES "SYSTEM"."GESTION_MATERIEL" ("NUM_SERIE") ENABLE;
