--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GESTION_EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EMPLOYE" 
   (	"CIN" NUMBER, 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"COLUMN3" VARCHAR2(20 BYTE), 
	"COLUMN4" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_LOCATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_LOCATION" 
   (	"ID_LOCATION" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"COLUMN3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_LOCAUX
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_LOCAUX" 
   (	"COORDONNES" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"COLUMN3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_MATERIEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_MATERIEL" 
   (	"NUM_SERIE" NUMBER, 
	"QUANTITER" NUMBER, 
	"PRIX" NUMBER, 
	"NOM_MATERIEL" VARCHAR2(20 BYTE), 
	"NOM_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_PUBLICITE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PUBLICITE" 
   (	"ID_PUBLICITE" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"COLUMN3" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_VEHICULE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_VEHICULE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"COLUMN3" NUMBER, 
	"COLUMN4" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_EMPLOYE
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_LOCATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_LOCAUX
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_MATERIEL
SET DEFINE OFF;
Insert into SYSTEM.GESTION_MATERIEL (NUM_SERIE,QUANTITER,PRIX,NOM_MATERIEL,NOM_FOURNISSEUR,TYPE) values ('1','1','1','a','u','r');
Insert into SYSTEM.GESTION_MATERIEL (NUM_SERIE,QUANTITER,PRIX,NOM_MATERIEL,NOM_FOURNISSEUR,TYPE) values ('1','0','0',null,null,null);
REM INSERTING into SYSTEM.GESTION_PUBLICITE
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_VEHICULE
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table GESTION_MATERIEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_MATERIEL" MODIFY ("NUM_SERIE" NOT NULL ENABLE);
